
/*
  Auto-generated by Spline (adapted for Remotion usage)
*/

import React from "react";
import useSpline from "@splinetool/r3f-spline";
import type { Material, BufferGeometry } from "three";

export const DEFAULT_SPLINE_SCENE_URL =
  "https://prod.spline.design/XJxJwmNEh18PAnhd/scene.splinecode";

type Variant = "desktop" | "mobile";

type SplineNode = {
  geometry?: BufferGeometry;
};

type SplineData = {
  nodes: Record<string, SplineNode>;
  materials: Record<string, Material>;
};

export const SplineImportedModel: React.FC<{
  sceneUrl?: string;
  variant?: Variant;
}> = ({ sceneUrl = DEFAULT_SPLINE_SCENE_URL }) => {
  const { nodes, materials } = useSpline(sceneUrl) as SplineData;

  return (
    <>
      <color attach="background" args={["#393939"]} />
      <group dispose={null}>
        <scene name="Scene 1">
          <mesh
            name="Shape"
            geometry={nodes.Shape.geometry}
            material={materials["Shape Material"]}
            castShadow
            receiveShadow
            position={[1510.29, 1384.58, 566.45]}
            rotation={[-0.83, 0.51, 0.53]}
          />

          <group name="Group 7" position={[1862.92, 909.83, 793.23]}>
            <mesh
              name="Rectangle 5"
              geometry={nodes["Rectangle 5"].geometry}
              material={materials["Rectangle 5 Material"]}
              castShadow
              receiveShadow
              rotation={[-0.83, 0.51, 0.53]}
              scale={[0.65, 0.6, 2.36]}
            />
            <mesh
              name="Text 15"
              geometry={nodes["Text 15"].geometry}
              material={materials["Text 15 Material"]}
              castShadow
              receiveShadow
              position={[-49.36, 31.44, 11]}
              rotation={[-0.83, 0.51, 0.53]}
              scale={[0.65, 0.6, 2.36]}
            />
            <mesh
              name="Text 17"
              geometry={nodes["Text 17"].geometry}
              material={materials["Text 17 Material"]}
              castShadow
              receiveShadow
              position={[-1.5, -29.47, 37.56]}
              rotation={[-0.83, 0.51, 0.53]}
              scale={[0.65, 0.6, 2.36]}
            />
            <mesh
              name="Text 16"
              geometry={nodes["Text 16"].geometry}
              material={materials["Text 16 Material"]}
              castShadow
              receiveShadow
              position={[-18.06, -0.47, 19.69]}
              rotation={[-0.83, 0.51, 0.53]}
              scale={[0.65, 0.6, 2.36]}
            />
          </group>

          <pointLight
            name="Point Light"
            castShadow
            intensity={1}
            distance={766}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={100}
            shadow-camera-far={100000}
            color="#fe9300"
            position={[129.57, 327.49, 0]}
          />

          <mesh
            name="Text 2"
            geometry={nodes["Text 2"].geometry}
            material={materials["Text 2 Material"]}
            castShadow
            receiveShadow
            position={[493.98, -178.93, 403.84]}
            rotation={[-0.76, 0.71, 0.56]}
          />

          <group
            name="Group 4"
            visible={false}
            position={[-223.45, -15, 105.75]}
          >
            <mesh
              name="Text"
              geometry={nodes.Text.geometry}
              material={materials["Text Material"]}
              castShadow
              receiveShadow
              position={[43.59, 68.5, -6.98]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cube"
              geometry={nodes.Cube.geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, 59, 0]}
            />
          </group>

          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[-370.97, 198.64, 300]}
          />

          <orthographicCamera name="1" far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  );
};

export default SplineImportedModel;
